version: "1.0"

llm:
  provider: "openai"
  model: "gpt-4"
  base_url: ""
  timeout: "60s"

scan:
  include:
    - "**/*.md"
  exclude: []

rules:
  fail_on_inconsistent: true
  confidence_threshold: 0.8

output:
  format: "text"
  color: true
